name: main

on:
  - push
  - pull_request

jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-systems }}
    strategy:
      matrix:
        operating-systems: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      # - name: Run tests
      #   run: make test

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
